---
- name: Change timeout
  lineinfile:
    path: /etc/default/grub
    state: present
    insertafter: EOF
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=3'
  notify: Update grub

- name: Change timeout style
  lineinfile:
    path: /etc/default/grub
    state: present
    insertafter: EOF
    regexp: '^GRUB_TIMEOUT_STYLE='
    line: 'GRUB_TIMEOUT_STYLE=menu'
  notify: Update grub

- name: Set grub options
  lineinfile:
    path: /etc/default/grub
    state: present
    insertafter: EOF
    regexp: '^GRUB_CMDLINE_LINUX=""'
    # Disable mitigations and enable intel acpi backlight
    line: 'GRUB_CMDLINE_LINUX="mitigations=off acpi_backlight=vendor"'
  notify: Update grub
