---
- name: Fix pacman gpg config
  lineinfile:
    path: "{{ sysprep_gpg_conf }}"
    state: present
    insertafter: EOF
    regexp: '^keyserver '
    line: 'keyserver {{ sysprep_gpg_conf_keyserver }}'
  when: sysprep_gpg_conf_fix | bool
  notify: Pacman refresh keys

- meta: flush_handlers

- name: Perform packages update
  include_tasks: update.yml
  when: sysprep_install_updates | bool

- name: Install base applications
  include_tasks: base_apps.yml

- name: Install video card utilities
  include_tasks: nvidia.yml

- name: Change shell for users
  user:
    name: "{{ item }}"
    shell: "/usr/bin/zsh"
  loop: "{{ users }}"

- include_tasks: grub.yml

- include_tasks: performance.yml

- name: Install VMWare guest services
  include_tasks: vmware_guest.yml
  when: (ansible_facts['virtualization_type'] | default('x')) == "VMWare" and (ansible_facts['virtualization_role'] | default('x')) == "guest"
