---
- name: Perform packages update
  include_tasks: update.yml
  when: sysprep_install_updates | bool

- name: Install base applications
  include_tasks: base_apps.yml

- name: Change shell for users
  user:
    name: "{{ item }}"
    shell: "/usr/bin/zsh"
  loop: "{{ users }}"

- include_tasks: grub.yml

- name: Install VMWare guest services
  include_tasks: vmware_guest.yml
  when: ansible_virtualization_type == "VMWare" and ansible_virtualization_role == "guest"

- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - avahi-daemon
