---
- name: Install docker from Manjaro repo
  pacman:
    name:
      - docker
      - docker-compose

- name: Install applications from AUR
  aur:
    name:
      - kitematic
  #   skip_installed: "{{ not soft_upgrade_aur }}"
  # when: soft_install_aur | bool
  become: true
  become_user: "{{ ansible_user }}"

- name: Create group docker
  group:
    name: docker
    state: present

- name: Add user to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start docker service
  systemd:
    name: docker
    state: started
    enabled: true
