---
- name: Create fonts download directory
  file:
    path: ~/.temp
    state: directory

- name: Get fonts arch stats
  stat:
    path: "~/.temp/{{ item }}.zip"
  register: fonts_arch_stats
  loop: "{{ nerd_fonts }}"

- name: Check not all fonts downloaded
  set_fact:
    not_all_fonts_exists: "{{ false in (fonts_arch_stats.results | map(attribute='stat.exists') | list) }}"

- name: Download fonts
  get_url:
    url: "{{ nerd_fonts_base_url }}/{{ item }}.zip"
    dest: "~/.temp/{{ item }}.zip"
    timeout: 30
  loop: "{{ nerd_fonts }}"
  when: not_all_fonts_exists | bool

- name: Create fonts directories
  file:
    path: "{{ fonts_dir }}/{{ item }}"
    state: directory
  loop: "{{ nerd_fonts }}"

- name: Extract fonts
  unarchive:
    src: "~/.temp/{{ item }}.zip"
    dest: "{{ fonts_dir }}/{{ item }}"
    remote_src: yes
  loop: "{{ nerd_fonts }}"
  notify: Rebuild fonts cache

- meta: flush_handlers
