i3wm_user: "{{ ansible_user }}"
i3wm_config_dir: ~/.config/i3
i3lock_images_dir: ~/.images
i3lock_image_size: 1024x768
i3lock_image_src_file: "{{ i3lock_images_dir }}/lockscreen.png"
i3lock_image_file: "{{ i3lock_images_dir }}/lockscreen-{{ i3lock_image_size }}.png"
i3status_config_dir: ~/.config/i3status

# i3status/polybar
i3wm_bar: "i3status"

# Swap left Alt and Super/Win keys
i3_swap_l_alt_l_super: false

# gxkb keyboard layout applet/switcher
gxkb_config_dir: ~/.config/gxkb
xresources_dir: .Xresources.d
xresources_fonts_path: "{{ xresources_dir }}/fonts"
xresources_urxvt_path: "{{ xresources_dir }}/urxvt"
xresources_xterm_path: "{{ xresources_dir }}/xterm"
xfce4_terminal_config_dir: ~/.config/xfce4/terminal

# Polybar settings
polybar_config_dir: ~/.config/polybar
polybar_eth_if: enp4s0
polybar_wifi_if: wlp5s0
polybar_power_supply_bat: BAT1
polybar_power_supply_adapter: ADP1
polybar_left: i3
polybar_center: mpd
polybar_right: filesystem xbacklight pulseaudio memory cpu wlan eth battery temperature date powermenu

i3_autostart_apps:
  - name: nm-applet
    file: nm-applet
    exec: nm-applet
    icon: nm-device-wireless
  - name: gxkb
    file: gxkb
    exec: gxkb
    icon: gxkb
  - name: Clipboard Manager
    file: xfce4-clipman
    exec: xfce4-clipman
    icon: xfce4-clipman-plugin
  - name: Dropbox
    file: dropbox
    exec: dropbox
    icon: dropbox
#  - name: Google Chrome
#    file: chrome
#    exec: /usr/bin/google-chrome-stable %U
#    startup_notify: 'true'
#    icon: google-chrome
#    wm_class: Google-chrome
  - name: Xfce Terminal
    file: xfce4-terminal
    exec: xfce4-terminal
    startup_notify: 'true'
    icon: utilities-terminal
  - name: Telegram Desktop
    file: telegram-desktop
    exec: telegram-desktop -- %u
    startup_notify: 'true'
    icon: telegram
    wm_class: TelegramDesktop
#  - name: Typora
#    file: typora
#    exec: typora %U
#    startup_notify: 'true'
#    icon: typora
