i3wm_user: "{{ ansible_user }}"
i3wm_config_dir: ~/.config/i3
i3lock_images_dir: ~/.images
i3lock_image_size: 1024x768
i3lock_image_src_file: "{{ i3lock_images_dir }}/lockscreen.png"
i3lock_image_file: "{{ i3lock_images_dir }}/lockscreen-{{ i3lock_image_size }}.png"
i3status_config_dir: ~/.config/i3status

# i3status/polybar
i3wm_bar: "i3status"

# Swap left Alt and Super/Win keys
i3_swap_l_alt_l_super: false

# gxkb keyboard layout applet/switcher
gxkb_config_dir: ~/.config/gxkb
xresources_dir: .Xresources.d
xresources_fonts_path: "{{ xresources_dir }}/fonts"
xresources_urxvt_path: "{{ xresources_dir }}/urxvt"
xresources_xterm_path: "{{ xresources_dir }}/xterm"
xfce4_terminal_config_dir: ~/.config/xfce4/terminal

# Polybar settings
polybar_config_dir: ~/.config/polybar
