---
- name: Change timeout
  lineinfile:
    path: /etc/default/grub
    state: present
    insertafter: EOF
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=3'
  notify: Update grub

- name: Change timeout style
  lineinfile:
    path: /etc/default/grub
    state: present
    insertafter: EOF
    regexp: '^GRUB_TIMEOUT_STYLE='
    line: 'GRUB_TIMEOUT_STYLE=menu'
  notify: Update grub
