---
# Install dotfiles
dotfiles_install: true
# Dotfiles directory starting from $HOME user directory
dotfiles_dir: dotfiles

# Link dotfiles to target directory starting from $HOME user directory
dotfiles_link_files:
  - src: git/gitconfig
    dest: .gitconfig
  - src: git/gitignore_global
    dest: .gitignore_global
  - src: shell/zshrc
    dest: .zshrc
  - src: shell/tmux.conf
    dest: .tmux.conf
  - src: shell/psqlrc
    dest: .psqlrc
  - src: shell/tmux-powerlinerc
    dest: .tmux-powerlinerc
  - src: shell/p10k.zsh
    dest: .p10k.zsh
  - src: shell/custom.sh
    dest: .tmux/themes/tmux-powerline/themes/custom.sh
  - src: vim/vimrc
    dest: .vimrc

# When true then all files dotfiles_copy_files will be copied
dotfiles_force_copy_files: false
dotfiles_copy_files:
  - src: mc/hotlist
    dest: .config/mc/hotlist
  - src: mc/ini
    dest: .config/mc/ini
  - src: mc/menu
    dest: .config/mc/menu
  - src: mc/panels.ini
    dest: .config/mc/panels.ini

dotfiles_link_dirs:
  - src: shell/custom
    dest: .custom
  - src: mc/skins
    dest: .local/share/mc/skins
  - src: vim/colors
    dest: .vim/colors

# VIM settings/plugins/colors/etc directory
vim_dir: .vim
