---
- name: Install frameworks from Manjaro repo
  pacman:
    name:
      - jre11-openjdk
      - go
      - dotnet-sdk

- name: Install applications from Manjaro repo
  pacman:
    name:
      # Dev
      - atom
      - docker
      - ansible
      - ansible-lint
      - remmina
      - freerdp
      - yarn
      - pandoc
      - plantuml
      - nvm
      - pyenv
      # Internet
      - firefox
      - telegram-desktop
      - transmission-gtk
      - shadowsocks-libev
      # Security
      - keepassxc

- name: Install applications from AUR
  aur:
    name:
      # Internet
      - google-chrome
      - teams
      - dropbox
      # Google drive console app
      - drive-bin
      # Dev
      - typora
      - visual-studio-code-bin
      - azuredatastudio
      - freemind
      - rbenv
      - ruby-build
      # - vmware-workstation
      # Mind map app instead of freemind
      #- freeplane
  when: soft_install_aur | bool
  become: true
  become_user: "{{ ansible_user }}"

- name: Create group docker
  group:
    name: docker
    state: present

- name: Add user to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create shadowsocks config dir
  file:
    path: "{{ shadowsocks_conf_dir }}"
    state: directory

- name: Create shadowsocks config
  copy:
    content: "{{ shadowsocks_config | to_nice_json(indent=2) }}"
    dest: "{{ shadowsocks_conf_file }}"
    mode: 0640
    owner: nobody

- name: Start services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - docker
    - 'shadowsocks-libev@{{ shadowsocks_service_name }}'
