---
- name: Remove packages
  pacman:
    name:
      - go
    state: absent

- name: Install frameworks from Manjaro repo
  pacman:
    name:
      - jre11-openjdk
      - go-pie
      - dotnet-sdk

- name: Install applications from Manjaro repo
  pacman:
    name:
      # Dev
      - atom
      - ansible
      - ansible-lint
      - remmina
      - freerdp
      - yarn
      - pandoc
      - plantuml
      - nvm
      - pyenv
      # Internet
      - firefox
      - telegram-desktop
      - transmission-gtk
      # Security
      - keepassxc
      # Office
      - gnome-calculator
      - meld
      - gendesk

- name: Install applications from AUR
  aur:
    name:
      # Internet
      - google-chrome
      - teams
      - dropbox
      - dropbox-cli
      # Google drive console app
      - drive-bin
      # Dev
      - typora
      - visual-studio-code-bin
      - azuredatastudio
      - freemind
      - rbenv
      - ruby-build
      # Mind map app instead of freemind
      # - freeplane
      - fontviewer
      # Heavy font manager app
      # - font-manager
      - xnviewmp
    skip_installed: "{{ not soft_upgrade_aur }}"
  when: soft_install_aur | bool
  become: true
  become_user: "{{ ansible_user }}"
