---
- name: Install frameworks from Manjaro repo
  pacman:
    name:
      - jre11-openjdk

- name: Install applications from Manjaro repo
  pacman:
    name:
      # Dev
      - atom
      - docker
      - ansible
      - ansible-lint
      - remmina
      - freerdp
      - yarn
      - pandoc
      - plantuml
      # Internet
      - telegram-desktop
      - transmission-gtk
      - shadowsocks-libev
      # Security
      - keepassxc

- name: Install applications from AUR
  aur:
    name:
      # Internet
      - google-chrome
      - teams
      - dropbox
      # Dev
      - typora
      - visual-studio-code-bin
      - azuredatastudio
      - freemind
      # Mind map app instead of freemind
      #- freeplane

  become: true
  become_user: "{{ ansible_user }}"

#     - remmina
#     - remmina-plugin-rdp
#     - remmina-plugin-secret
#     - remmina-plugin-vnc

- name: Add user to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - docker
