---
- name: Disable dropbox autostart feature
  shell: dropbox-cli autostart n
  failed_when: false
  changed_when: false

- name: Find non i3 files in autostart directory
  find:
    paths: ~/.config/autostart
    patterns: '^.*\.desktop$'
    use_regex: true
  register: autostart_find_results
  become: true
  become_user: "{{ i3wm_user }}"

- name: Deleting files from autostart directory
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ autostart_find_results.files }}"
  loop_control:
    label: "{{ item.path }}"
  become: true
  become_user: "{{ i3wm_user }}"

- name: Find all desktop files in /etc/xdg/autostart
  find:
    paths: /etc/xdg/autostart
    patterns: '*.desktop'
  register: autostart_global_find_results

- name: Deleting files from global autostart directory
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ autostart_global_find_results.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Create autostart files
  template:
    src: app.desktop.j2
    dest: "~/.config/autostart/i3-{{ item.file }}.desktop"
  loop: "{{ i3_autostart_apps }}"
  loop_control:
    label: "{{ item.file }}"
  become: true
  become_user: "{{ i3wm_user }}"
