---
- name: Upload SSH key
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_key_master }}') }}"
  loop: "{{ users }}"
  when: ssh_key_master is defined

- name: Upload sudoers file
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/90-{{ ansible_user }}"
